### ISSUE TITLE
[Bug]: BetterF3 Crashes on Fabric 1.16.5 When Trying To Open The Menu

### ISSUE THREAD

**Issue by ghost** [TreyRuffy/BetterF3#21]
### Describe the Bug

Alright. So in short it crashes when press F3 ingame. Super weird but it happens. Instantly exits the game and gives an error code.   

### Steps to Reproduce

Open curseforge and make a 1.16.5 profile.
Install BetterF3-1.5.0-Fabric-1.16.5.jar (Of course all of the dependencies too.) 
Start the profile. 
Create a new world. 
And Boom. Press F3 and the rest is history.

### Expected Behavior

The BetterF3 Menu to pop up. Right? 

### Screenshots

I dont have any.

### Modloader Type

Fabric

### Modloader Version

Fabric - 0.14.21

### Mod Version

 BetterF3-1.5.0-Fabric-1.16.5.jar

### Log Output

```shell
[17:42:06] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.14.21
[17:42:06] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[17:42:06] [main/WARN]: Warnings were found!
 - Mod 'BetterF3' (betterf3) 1.5.0 recommends version 1.16.3 or later of modmenu, which is missing!
	 - You should install version 1.16.3 or later of modmenu for the optimal experience.
[17:42:06] [main/INFO]: Loading 60 mods:
	- betterf3 1.5.0
	   \-- fabric-resource-loader-v0 0.4.8+3cc0f0907d
	- cloth-config2 4.17.101
	   \-- cloth-basic-math 0.6.1
	- fabric 0.42.0+1.16
	   |-- fabric-api-base 0.4.0+3cc0f0907d
	   |-- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d
	   |-- fabric-biome-api-v1 3.1.13+3cc0f0907d
	   |-- fabric-blockrenderlayer-v1 1.1.6+3cc0f0907d
	   |-- fabric-command-api-v1 1.1.3+3cc0f0907d
	   |-- fabric-commands-v0 0.2.3+3cc0f0907d
	   |-- fabric-containers-v0 0.1.12+3cc0f0907d
	   |-- fabric-content-registries-v0 0.2.5+3cc0f0907d
	   |-- fabric-crash-report-info-v1 0.1.4+3cc0f0907d
	   |-- fabric-dimensions-v1 2.0.8+3cc0f0907d
	   |-- fabric-entity-events-v1 1.2.4+3cc0f0907d
	   |-- fabric-events-interaction-v0 0.4.5+3cc0f0907d
	   |-- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d
	   |-- fabric-game-rule-api-v1 1.0.7+3cc0f0907d
	   |-- fabric-item-api-v1 1.2.2+3cc0f0907d
	   |-- fabric-item-groups-v0 0.3.1+3cc0f0907d
	   |-- fabric-key-binding-api-v1 1.0.5+3cc0f0907d
	   |-- fabric-keybindings-v0 0.2.2+3cc0f0907d
	   |-- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d
	   |-- fabric-loot-tables-v1 1.0.3+3cc0f0907d
	   |-- fabric-mining-levels-v0 0.1.4+3cc0f0907d
	   |-- fabric-models-v0 0.3.1+3cc0f0907d
	   |-- fabric-networking-api-v1 1.0.5+3cc0f0907d
	   |-- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d
	   |-- fabric-networking-v0 0.3.3+3cc0f0907d
	   |-- fabric-object-builder-api-v1 1.9.6+3cc0f0907d
	   |-- fabric-object-builders-v0 0.7.3+3cc0f0907d
	   |-- fabric-particles-v1 0.2.5+3cc0f0907d
	   |-- fabric-registry-sync-v0 0.7.6+3cc0f0907d
	   |-- fabric-renderer-api-v1 0.4.5+3cc0f0907d
	   |-- fabric-renderer-indigo 0.4.5+3cc0f0907d
	   |-- fabric-renderer-registries-v1 2.3.1+3cc0f0907d
	   |-- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d
	   |-- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d
	   |-- fabric-rendering-v0 1.1.3+3cc0f0907d
	   |-- fabric-rendering-v1 1.6.1+3cc0f0907d
	   |-- fabric-resource-loader-v0 0.4.8+3cc0f0907d
	   |-- fabric-screen-api-v1 1.0.1+3cc0f0907d
	   |-- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d
	   |-- fabric-structure-api-v1 1.1.12+3cc0f0907d
	   |-- fabric-tag-extensions-v0 1.1.2+3cc0f0907d
	   |-- fabric-textures-v0 1.0.7+3cc0f0907d
	   |-- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d
	   \-- fabric-transfer-api-v1 1.5.0+3cc0f0907d
	- fabricloader 0.14.21
	- inventoryhud 3.4.1
	- java 8
	- minecraft 1.16.5
	- mousetweaks 2.22
	- roughlyenoughitems 5.12.385
	   |-- cloth-client-events-v0 1.6.59
	   |-- roughlyenoughitems-api 5.12.385
	   |    \-- cloth-client-events-v0 1.6.59
	   |-- roughlyenoughitems-default-plugin 5.12.385
	   |    \-- cloth-client-events-v0 1.6.59
	   \-- roughlyenoughitems-runtime 5.12.385
	        \-- cloth-client-events-v0 1.6.59
	- skinlayers 1.1.0
	- waila 1.9.22
[17:42:06] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/E:/Minecraft/Install/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[17:42:11] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:42:12] [main/INFO]: Setting user: xitronus
[17:42:13] [main/INFO]: Discovered plugin waila:core provided by waila at mcp.mobius.waila.addons.core.PluginCore
[17:42:13] [main/INFO]: Discovered plugin waila:vanilla provided by waila at mcp.mobius.waila.addons.minecraft.PluginMinecraft
[17:42:13] [main/INFO]: Registering plugin at mcp.mobius.waila.addons.core.PluginCore
[17:42:13] [main/INFO]: Registering plugin at mcp.mobius.waila.addons.minecraft.PluginMinecraft
[17:42:13] [main/INFO]: [BetterF3] Loading...
[17:42:13] [main/INFO]: [BetterF3] All done!
[17:42:13] [main/INFO]: [Indigo] Registering Indigo renderer!
[17:42:13] [main/INFO]: [STDOUT]: Inventory HUD + has been initialized!
[17:42:13] [main/INFO]: [STDOUT]: [Mouse Tweaks] Main.initialize()
[17:42:13] [main/INFO]: [STDOUT]: [Mouse Tweaks] Generating the config file at: E:\Minecraft\Instances\Minecraft SMP\config\MouseTweaks.cfg
[17:42:13] [main/INFO]: [STDOUT]: [Mouse Tweaks] Created the config file.
[17:42:13] [main/INFO]: [STDOUT]: [Mouse Tweaks] Initialized.
[17:42:14] [main/INFO]: Config loaded.
[17:42:14] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[17:42:17] [main/INFO]: Narrator library for x64 successfully loaded
[17:42:17] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (BetterF3, Cloth Config v4, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Levels (v0), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking Block Entity (v0), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Object Builders (v0), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Structure API (v1), Fabric Tag Extensions (v0), Fabric Textures (v0), Fabric Tool Attribute API (v1), Fabric Transfer API (v1), Fabric Loader, Inventory HUD +, Roughly Enough Items, REI (Runtime), 3d Skin Layers, Hwyla)
[17:42:19] [main/INFO]: OpenAL initialized.
[17:42:19] [main/INFO]: Sound engine started
[17:42:20] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[17:42:20] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[17:42:20] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[17:42:20] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[17:42:20] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[17:42:20] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[17:42:20] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[17:42:21] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[17:42:21] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[17:42:21] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[17:44:03] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[17:44:03] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[17:44:03] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[17:44:03] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[17:44:03] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[17:44:03] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Tool Attribute API (v1))
[17:44:03] [main/INFO]: Loaded 7 recipes
[17:44:03] [main/INFO]: Loaded 927 advancements
[17:44:03] [main/INFO]: Applied 0 biome modifications to 0 of 79 new biomes in 1.228 ms
[17:44:04] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:44:04] [Server thread/INFO]: Starting integrated minecraft server version 1.16.5
[17:44:04] [Server thread/INFO]: Generating keypair
[17:44:06] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[17:44:06] [main/INFO]: Preparing spawn area: 0%
[17:44:07] [main/INFO]: Preparing spawn area: 2%
[17:44:07] [main/INFO]: Preparing spawn area: 6%
[17:44:08] [main/INFO]: Preparing spawn area: 13%
[17:44:08] [main/INFO]: Preparing spawn area: 19%
[17:44:09] [main/INFO]: Preparing spawn area: 28%
[17:44:09] [main/INFO]: Preparing spawn area: 38%
[17:44:10] [main/INFO]: Preparing spawn area: 46%
[17:44:10] [main/INFO]: Preparing spawn area: 50%
[17:44:11] [main/INFO]: Preparing spawn area: 60%
[17:44:11] [main/INFO]: Preparing spawn area: 70%
[17:44:12] [main/INFO]: Preparing spawn area: 79%
[17:44:12] [main/INFO]: Preparing spawn area: 89%
[17:44:13] [main/INFO]: Preparing spawn area: 97%
[17:44:13] [main/INFO]: Time elapsed: 6553 ms
[17:44:13] [Server thread/INFO]: Changing view distance to 13, from 10
[17:44:14] [Server thread/INFO]: xitronus[local:E:d16dbe91] logged in with entity id 279 at (241.5, 65.0, 75.5)
[17:44:14] [Server thread/INFO]: xitronus joined the game
[17:44:14] [Server thread/INFO]: Saving and pausing game...
[17:44:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[17:44:14] [REI-SyncRecipes/INFO]: Reloading REI, registered 2 plugins: roughlyenoughitems:default_runtime_plugin, roughlyenoughitems:default_plugin
[17:44:14] [REI-SyncRecipes/INFO]: Applied Check Tags for potion in 6ms.
[17:44:14] [main/INFO]: Loaded 0 advancements
[17:44:14] [REI-SyncRecipes/INFO]: Reloaded 1247 stack entries, 1339 recipes displays, 3 exclusion zones suppliers, 5 overlay deciders, 1 visibility handlers and 16 categories (Crafting, Smelting, Smoking, Blasting, Campfire, Stone Cutting, Fuel, Brewing, Composting, Stripping, Smithing, Beacon Base, Beacon Payment, Tilling, Pathing, Information) in 121ms.
[17:44:14] [main/INFO]: [STDOUT]: InvGUI Initialized
[17:44:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[17:44:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[17:45:02] [main/INFO]: Loaded 4 advancements
[17:45:03] [main/FATAL]: Unreported exception thrown!
java.lang.IllegalAccessError: tried to access method net.minecraft.class_761.method_3246()I from class me.cominixo.betterf3.modules.ChunksModule
	at me.cominixo.betterf3.modules.ChunksModule.update(ChunksModule.java:112) ~[BetterF3-1.5.0-Fabric-1.16.5.jar:?]
	at net.minecraft.class_340.newLeftText(class_340.java:715) ~[client-intermediary.jar:?]
	at net.minecraft.class_340.handler$zza000$betterf3$renderLeftText(class_340.java:894) ~[client-intermediary.jar:?]
	at net.minecraft.class_340.method_1847(class_340.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_340.method_1846(class_340.java:111) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:267) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:597) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1048) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.21.jar:?]
[17:45:05] [Server thread/INFO]: Stopping server
[17:45:05] [Server thread/INFO]: Saving players
[17:45:05] [Server thread/INFO]: xitronus lost connection: Disconnected
[17:45:05] [Server thread/INFO]: xitronus left the game
[17:45:05] [Server thread/INFO]: Stopping singleplayer server as player logged out
[17:45:05] [Server thread/INFO]: Saving worlds
[17:45:05] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[17:45:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[17:45:06] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[17:45:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[17:45:06] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[17:45:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[17:45:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[17:45:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[17:45:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
```

### Additional Context

^^^  Idk what this is but i hope its the right thing.

**Comment by ArtOfCombat** [comment]
Similar issue on forge for 1.16.5
