### ISSUE TITLE
[Bug]: 1.19.2 indexOutOfbounds Forge

### ISSUE THREAD

**Issue by CKY-** [TreyRuffy/BetterF3#38]
### Describe the Bug

I may have reported this to the wrong repo. not knowing that the forge version is a fork of the fabric version..
https://github.com/cominixo/BetterF3/issues/152

### Steps to Reproduce

have alex mobs friends or foe or any other mob mod installed and hit F3

### Expected Behavior

index to be inbounds and not looking past the length of the array 

### Modloader Type

Minecraft Forge

### Modloader Version

43.3.2

### Mod Version

4.0.0

### Log Output

```shell
[02Nov2023 01:24:47.723] [Render thread/ERROR] [net.minecraftforge.client.gui.overlay.ForgeGui/]: Error rendering overlay 'minecraft:debug_text'
java.lang.IndexOutOfBoundsException: Index 10 out of bounds for length 10
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at me.cominixo.betterf3.modules.EntityModule.update(EntityModule.java:82) ~[BetterF3-4.0.0-Forge-1.19.2.jar%23652!/:?]
	at net.minecraft.client.gui.components.DebugScreenOverlay.newLeftText(DebugScreenOverlay.java:1667) ~[client-1.19.2-20220805.130853-srg.jar%231061!/:?]
	at net.minecraft.client.gui.components.DebugScreenOverlay.handler$cfd001$renderLeftText(DebugScreenOverlay.java:1845) ~[client-1.19.2-20220805.130853-srg.jar%231061!/:?]
	at net.minecraft.client.gui.components.DebugScreenOverlay.m_94076_(DebugScreenOverlay.java) ~[client-1.19.2-20220805.130853-srg.jar%231061!/:?]
	at net.minecraft.client.gui.components.DebugScreenOverlay.m_94056_(DebugScreenOverlay.java:120) ~[client-1.19.2-20220805.130853-srg.jar%231061!/:?]
	at net.minecraftforge.client.gui.overlay.ForgeGui.handler$cfk000$customDebugMenu(ForgeGui.java:763) ~[forge-1.19.2-43.3.2-universal.jar%231066!/:?]
	at net.minecraftforge.client.gui.overlay.ForgeGui.renderHUDText(ForgeGui.java:459) ~[forge-1.19.2-43.3.2-universal.jar%231066!/:?]
	at net.minecraftforge.client.gui.overlay.VanillaGuiOverlay.lambda$static$17(VanillaGuiOverlay.java:153) ~[forge-1.19.2-43.3.2-universal.jar%231066!/:?]
	at net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:141) ~[forge-1.19.2-43.3.2-universal.jar%231066!/:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar%23121!/:?]
	at net.minecraftforge.client.gui.overlay.ForgeGui.m_93030_(ForgeGui.java:136) ~[forge-1.19.2-43.3.2-universal.jar%231066!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:876) ~[client-1.19.2-20220805.130853-srg.jar%231061!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%231061!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%231061!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%231061!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%231061!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.2.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
```

**Comment by TreyRuffy** [comment]
This was fixed in 4.0.1.
