### ISSUE TITLE
[Bug]: BetterF3 does not support NeoForge 1.20.2+

### ISSUE THREAD

**Issue by Omnimetatron** [TreyRuffy/BetterF3#41]
### Describe the Bug

MC 1.20.2 Neoforged, seems to be asking for regular Forge.

### Steps to Reproduce

Load BetterF3 8.0.1 in Neoforged 1.20.2 (20.2.48)

### Expected Behavior

Minecraft to load succesfully.

### Modloader Type

Minecraft Forge

### Modloader Version

neoforge-20.2.48-beta-universal.jar

### Mod Version

8.0.1

### Log Output

```shell
---- Minecraft Crash Report ----
// There are four lights!

Time: 2023-11-12 18:23:39
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.neoforged.neoforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:54) ~[neoforge-20.2.48-beta-universal.jar%23183!/:?] {re:classloading}
	at net.neoforged.neoforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:132) ~[neoforge-20.2.48-beta-universal.jar%23183!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.buildInitialScreens(Minecraft.java:641) ~[client-1.20.2-20231019.002635-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.onGameLoadFinished(Minecraft.java:614) ~[client-1.20.2-20231019.002635-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.onResourceLoadFinished(Minecraft.java:609) ~[client-1.20.2-20231019.002635-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:597) ~[client-1.20.2-20231019.002635-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.Util.ifElse(Util.java:418) ~[client-1.20.2-20231019.002635-srg.jar%23178!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$6(Minecraft.java:591) ~[client-1.20.2-20231019.002635-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.neoforged.neoforge.client.loading.NeoForgeLoadingOverlay.render(NeoForgeLoadingOverlay.java:145) ~[neoforge-20.2.48-beta-universal.jar%23183!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1091) ~[client-1.20.2-20231019.002635-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1200) ~[client-1.20.2-20231019.002635-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.run(Minecraft.java:776) ~[client-1.20.2-20231019.002635-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:231) ~[neoforge-20.2.48-beta.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-1.0.10.jar:1.0] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-1.0.10.jar:1.0] {}
	at net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-1.0.10.jar:1.0] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-1.0.10.jar:1.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.neoforged.neoforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:57) ~[neoforge-20.2.48-beta-universal.jar%23183!/:?] {re:classloading}
-- NO MOD INFO AVAILABLE --
Details:
	Mod File: NO FILE INFO
	Failure message: Mod File BetterF3-8.0.1-Forge-1.20.2.jar needs language provider javafml:48 or above to load
		We have found 1.0
	Mod Version: NO MOD INFO AVAILABLE
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE
Stacktrace:
	at net.neoforged.neoforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:57) ~[neoforge-20.2.48-beta-universal.jar%23183!/:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:computing_frames}
	at net.neoforged.neoforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[neoforge-20.2.48-beta-universal.jar%23183!/:?] {re:classloading}
	at net.neoforged.neoforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:132) ~[neoforge-20.2.48-beta-universal.jar%23183!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.buildInitialScreens(Minecraft.java:641) ~[client-1.20.2-20231019.002635-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.onGameLoadFinished(Minecraft.java:614) ~[client-1.20.2-20231019.002635-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.onResourceLoadFinished(Minecraft.java:609) ~[client-1.20.2-20231019.002635-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:597) ~[client-1.20.2-20231019.002635-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.Util.ifElse(Util.java:418) ~[client-1.20.2-20231019.002635-srg.jar%23178!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$6(Minecraft.java:591) ~[client-1.20.2-20231019.002635-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.neoforged.neoforge.client.loading.NeoForgeLoadingOverlay.render(NeoForgeLoadingOverlay.java:145) ~[neoforge-20.2.48-beta-universal.jar%23183!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1091) ~[client-1.20.2-20231019.002635-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1200) ~[client-1.20.2-20231019.002635-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.run(Minecraft.java:776) ~[client-1.20.2-20231019.002635-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:231) ~[neoforge-20.2.48-beta.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-1.0.10.jar:1.0] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-1.0.10.jar:1.0] {}
	at net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-1.0.10.jar:1.0] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-1.0.10.jar:1.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 6803599576 bytes (6488 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon RX 5700 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x731f
	Graphics card #0 versionInfo: DriverVersion=31.0.22017.3004
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 22741.03
	Virtual memory used (MB): 20404.95
	Swap memory total (MB): 6406.86
	Swap memory used (MB): 343.47
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xms8G -Xmx8G -XX:+UseShenandoahGC -XX:+AlwaysPreTouch
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		loader-1.0.10.jar slf4jfixer PLUGINSERVICE 
		loader-1.0.10.jar object_holder_definalize PLUGINSERVICE 
		loader-1.0.10.jar runtime_enum_extender PLUGINSERVICE 
		loader-1.0.10.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-9.0.3.jar accesstransformer PLUGINSERVICE 
		loader-1.0.10.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		lowcodefml@1.0
		minecraft@1.0
		javafml@1.0
	Mod List: 
		client-1.20.2-20231019.002635-srg.jar             |Minecraft                     |minecraft                     |1.20.2              |NONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		neoforge-20.2.48-beta-universal.jar               |NeoForge                      |neoforge                      |20.2.48-beta        |NONE      |Manifest: NOSIGNATURE
```

**Comment by TreyRuffy** [comment]
BetterF3 currently does not have support for NeoForge. I am waiting on cloth config and a more stable of NeoForge before I can support it

**Comment by MaxwellRU** [comment]
any progress on NeoForge support?

**Comment by TreyRuffy** [comment]
Added 1.20.2 support. Hopefully, more can be added within the next week or so!

**Comment by TreyRuffy** [comment]
Just got it working for 1.20.3 and 1.20.4! Pushed the branch and you'll see it on Modrinth and CurseForge later tonight!
